### ISSUE TITLE
CircleCI: don't do `apt dist-upgrade -y`

### ISSUE THREAD

**Issue by fingolfin** [homalg-project/homalg_project#283] opened 2019-08-27 16:24 UTC
I noticed that you are doing `apt dist-upgrade -y` in your CircleCI config. I'd advise against that, it defeats the purpose of having reproducible tests. It also slows things down needlessly. Better would be to update the Docker image that is being used.

**Comment by mohamed-barakat** [comment] 2019-08-29 10:03
I agree. I'll wait for @zickgraf to confirm.

**Comment by zickgraf** [comment] 2019-09-06 10:23
The reason for doing this is the following: We need the packages `texlive-latex-extra`, `texlive-science` and `curl`, which are not installed in the gap docker image. Just calling `apt-get install texlive-latex-extra texlive-science curl` without `apt-get update` leads to errors if newer versions of the packages are released and the older versions are not available for download anymore. So we also have to call `apt-get update`. But after calling `apt-get update`, the installation of the packages might pull in arbitrary updates and thus create an environment which is hard to reproduce locally. Thus, I decided to simply update all packages.

I agree that an intermediate docker image with `texlive-latex-extra`, `texlive-science` and `curl` included would be a cleaner solution. However, until now I never had problems with reproducibility because of this, so from my point of view the maintenance burden of an additional docker image would not be worth it.

**Comment by zickgraf** [comment] 2019-10-22 11:09
I have talked to @fingolfin and we have decided to close the issue.

**Closed by zickgraf** 2019-10-22 11:09 UTC
